name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_sqlite

    - name: Install Composer dependencies
      run: composer install

    - name: Create SQLite database file
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Overwrite secrets in .env
      run: |
        sed -i "s|^JWT_SECRET=.*|JWT_SECRET=${{ secrets.JWT_SECRET }}|" .env
        sed -i "s|^JWT_REFRESH_SECRET=.*|JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}|" .env
        sed -i "s|^DB_DRIVER=.*|DB_DRIVER=${{ secrets.DB_DRIVER }}|" .env
        sed -i "s|^DB_TYPE=.*|DB_TYPE=${{ secrets.DB_TYPE }}|" .env
        sed -i "s|^DB_PATH=.*|DB_PATH=${{ secrets.DB_PATH }}|" .env
        sed -i "s|^DB_HOST=.*|DB_HOST=${{ secrets.DB_HOST }}|" .env
        sed -i "s|^DB_PORT=.*|DB_PORT=${{ secrets.DB_PORT }}|" .env
        sed -i "s|^DB_NAME=.*|DB_NAME=${{ secrets.DB_NAME }}|" .env
        sed -i "s|^DB_USER=.*|DB_USER=${{ secrets.DB_USER }}|" .env
        sed -i "s|^DB_PASSWORD=.*|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|" .env

    - name: Run Doctrine migrations
      run: vendor/bin/doctrine-migrations migrate --no-interaction

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --level=5

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --colors=always
