name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_sqlite

    - name: Install Composer dependencies
      run: composer install

    - name: Create SQLite database file
      run:
        mkdir -p database
        touch database/database.sqlite

    - name: Run Doctrine migrations
      run: vendor/bin/doctrine-migrations migrate --no-interaction

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --level=5

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --colors=always
