name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_sqlite

    - name: Install Composer dependencies
      run: composer install

    - name: Create SQLite database file
      run:
        mkdir -p database
        touch database/database.sqlite

    - name: Create .env from secrets
      run:
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}" >> .env
        echo "DB_DRIVER=pdo_sqlite" >> .env
        echo "DB_TYPE=sqlite" >> .env
        echo "DB_PATH=${{ secrets.DB_PATH }}" >> .env
        echo "DB_HOST=" >> .env
        echo "DB_PORT=" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

    - name: Debug .env
      run: cat .env    

    - name: Run Doctrine migrations
      run: vendor/bin/doctrine-migrations migrate --no-interaction

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --level=5

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --colors=always
